### ISSUE TITLE
Password auth to script

### ISSUE THREAD

**Issue by alfonsoh** [tekperfect/TerraForm-Docsify#2]
The jamf directory contains several scripts that need to be combined into one script and script 04 needs to have the database password provided to it along with several other prompts. Can you create a file that has the passwords and associate the variables in the script to that file so we can create a .getignore for it

**Comment by NinjaAung** [comment]
Latest Push to master reflect these chnages

**Comment by NinjaAung** [comment]
Seperate:
        - Transit Gateway
        - VPC
