### ISSUE TITLE
Break out windows+linux code tf files

### ISSUE THREAD

**Issue by alfonsoh** [tekperfect/TerraForm-Docsify#4]
Can you review the current tf files in the linux+windows directory and make sure the Linux one only deploys a Linux box, the Windows one does the same, and you make it so we can deploy a VPC, and transit gateway separately from the other tf files.

**Comment by NinjaAung** [comment]
Seperate:
- Transit Gateway
- VPC

**Comment by NinjaAung** [comment]
Separated tgw and vpc into their own directories [here](https://github.com/tekperfect/TerraForm-Docsify/tree/main/example/vpc%2Btgw)

**Comment by NinjaAung** [comment]
Still need to test if linux and window terraform works, but I'm pretty sure they do
