### ISSUE TITLE
Deploy script prep

### ISSUE THREAD

**Issue by alfonsoh** [tekperfect/TerraForm-Docsify#5]
Please use the following deploy script to prepare the class to use these examples. I would like them to reference the terraform.tfvars file when deploying their code.

https://pastebin.com/nGiEtbSZ

#!/bin/bash
cp ~/secrets/terraform.tfvars.asc .
gpg --decrypt --nosymkey-cache --output ./terraform.tfvars ./terraform.tfvars.asc
terraform plan
terraform apply
sleep 60s
rm ./terraform.tfvars*

**Comment by NinjaAung** [comment]
Done! I updated the script to a more streamlined bash script check [here](https://github.com/tekperfect/TerraForm-Docsify/blob/main/example/tfsecret). I will put a readme file associated to the usage of the file.

The jist:

- Added bash script to tfsecret
- Bash script is expanded
- Updated all terraform files to handle it
- Fixed keypair error (commented it out, suggest create a keypair in aws for it)

What I need to do:

- add video of usage
- create a doc for asynchronous work for Saturday
